name: Build and Deploy ASP.NET Core App

on:
push:
branches:
•  main


jobs:
build:
runs-on: ubuntu-latest

steps:
•  name: Checkout code

uses: actions/checkout@v2

•  name: Setup .NET Core

uses: actions/setup-dotnet@v1
with:
dotnet-version: 6.0.x

•  name: Restore dependencies

run: dotnet restore

•  name: Build

run: dotnet build --configuration Release --no-restore

•  name: Publish

run: dotnet publish --configuration Release --no-build --output ./publish

•  name: Deploy to GitHub Pages

uses: peaceiris/actions-gh-pages@v3
with:
github_token: ${{ secrets.GITHUB_TOKEN }}
publish_dir: ./publish